name: 10-1-artifact-upload 
on:
    workflow_dispatch:
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the code 
          uses: actions/checkout@v3
        - name: Setup Java 21
          uses: actions/setup-java@v4
          with: 
            java-version: 21
            distribution: temurin
            cache: maven   # ~/.m2 artifacts 
        - name: Build and package
          run: mvn package -DskipTests
        - name: Upload Build Artifact 
          uses: actions/upload-artifact@v4
          with: 
            name: build-artifact
            path: target/*.jar
            retention-days: 7

