name: Pull Request Event
on:
    pull_request: 
jobs:
    show-information:
        name: Pull Request Trigger info 
        runs-on: ubuntu-latest
        steps:
            - name : Show Pull Request Information 
              run: |
               echo "============================"
               echo "Details of My Work flow "
               echo "Event Name is :::::     ${{github.event_name}}"
               echo "Source branch is :::::   ${{github.head_ref}}"
               echo "Target branch is :::::::  ${{github.base_ref}}"
               echo "Repository Name is ::::   ${{github.repository}}"
               echo "Actor is ::::::            ${{github.actor}}"
               echo "Commit SHA is ::::::::::    ${{github.sha}}"
